travis:
  secure:
    BINSTAR_TOKEN: TGifuQSbPtsvO0J6oXsOj04NLbwxltGAzvDBMqvOeRwTzzvhGFEFrXQLAeEIdbz+Xv/FJYhqwFHQjXQiHS71pd9R8TXNS9xGB6ywT2KeiWOyhXuvtSwXUwnhcalg/L6sorM5g1MmQVA7vK0lHzfapIZuWX2ax06Ta1AC30VfkmlbzurTuZG7eYywtIb3Q6KGKBAEUbvMi5dQ0w0SF0wLsOYKd9DGUbIxvkvcrH0SSj5GuyzFgvlxNLaNK1NYOu+U9oRTkl8txZxgS/Q2mqxeGSdp/3hvTT00YrXDJ7Wy1K8Iy5nbAu4lxw46eNuTL0n2PXIX2o9uEWFZybI1SOFPS68Oc54S5kWv3fhHEgDQUqBDLvoDSj/naQa+CxolZGQQC/f8Aw9YsH/Tev2DE9sBW18lUIQbHPZDaK6xvz/4+OX93Rut7JLxYFI1WW50l7b/ME2Cx/b4RN7wtgfHo7diPIb4fsupapdaiTn7Z6rGe5qf/HnoMLfz2rkZ3l/9sBIg9l5uRfWRhbASaLgcJ/1QgPstX2Vu731LmTjc0Z1jJ2xY+UYM9PuMUox9jE1pbC7P5dPOLItdiXXaLfPzXiV/fI8pNPIj40GZsBHk9OOv++T6zjOs99fhVbnpqqX/Afs2yrlscJRwcGONhyI69iMsKAKGF/4we6JYwkRdiLKggc0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
